// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUoXthoUX4gy6LGK8khZsdl1XFWH5wQlM',
    appId: '1:722997657550:web:f3be0863880e319c4af59f',
    messagingSenderId: '722997657550',
    projectId: 'libra-connects',
    authDomain: 'libra-connects.firebaseapp.com',
    storageBucket: 'libra-connects.firebasestorage.app',
    measurementId: 'G-841BNEQV1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_IZTuMQuY5Ap9HlZ2AJVmO7goS17aITI',
    appId: '1:722997657550:android:738224f4be95a35a4af59f',
    messagingSenderId: '722997657550',
    projectId: 'libra-connects',
    storageBucket: 'libra-connects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhp58DaHw40EiCl1jEu_TuKk5kEuVFUU',
    appId: '1:722997657550:ios:b5b7e47be3b1a6314af59f',
    messagingSenderId: '722997657550',
    projectId: 'libra-connects',
    storageBucket: 'libra-connects.firebasestorage.app',
    iosBundleId: 'com.example.libraconnectsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhp58DaHw40EiCl1jEu_TuKk5kEuVFUU',
    appId: '1:722997657550:ios:b5b7e47be3b1a6314af59f',
    messagingSenderId: '722997657550',
    projectId: 'libra-connects',
    storageBucket: 'libra-connects.firebasestorage.app',
    iosBundleId: 'com.example.libraconnectsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUoXthoUX4gy6LGK8khZsdl1XFWH5wQlM',
    appId: '1:722997657550:web:5f4e1a9b443011a24af59f',
    messagingSenderId: '722997657550',
    projectId: 'libra-connects',
    authDomain: 'libra-connects.firebaseapp.com',
    storageBucket: 'libra-connects.firebasestorage.app',
    measurementId: 'G-0K9FVL6RVX',
  );
}
